### Overview of Python

In [10]:
# f string
spam = "sexy lips"
print(f"Text: Pablo has {spam}!")

Text: Pablo has sexy lips!


In [11]:
# Dictionary
var7 = {'Topic': 'Data Science', 'Language': 'Python'}
print(var7)

{'Topic': 'Data Science', 'Language': 'Python'}


In [12]:
var7['Publisher'] = 'Packt'
print(var7)

{'Topic': 'Data Science', 'Language': 'Python', 'Publisher': 'Packt'}


In [13]:
del var7['Publisher']
print(var7)

{'Topic': 'Data Science', 'Language': 'Python'}


In [14]:
print(var7)

{'Topic': 'Data Science', 'Language': 'Python'}


### Creating a Dictionary That Will Contain Machine Learning Algorithms

In [15]:
# List called algorithm
algorithm = ['Linear Regression', 'Logistic Regression', 'RandomForest', 'a3c']

In [16]:
# List called Learning
Learning = ['Supervised', 'Supervised', 'Supervised', 'Reinforcement']

In [17]:
# List called algorithm_type
algorithm_type = ['Regression', 'Classification', 'Regression or Classification', 'Game AI']

In [18]:
# add k-means to algorithm
algorithm.append('K.means')

In [19]:
print(algorithm)

['Linear Regression', 'Logistic Regression', 'RandomForest', 'a3c', 'K.means']


In [20]:
# add unspervised to Learning
Learning.append('Unsupervised')

In [21]:
print(Learning)

['Supervised', 'Supervised', 'Supervised', 'Reinforcement', 'Unsupervised']


In [22]:
# add clustering to algorithm_type
algorithm_type.append('Clustering')

In [23]:
print(algorithm_type)

['Regression', 'Classification', 'Regression or Classification', 'Game AI', 'Clustering']


In [24]:
# an empty dictionary string
machine_learning = {}

In [25]:
# Create a new item in machine_learning with the key as algorithm
#and the value as all the items from the algorithm list
machine_learning['algorithm'] = algorithm

In [26]:
print(machine_learning)

{'algorithm': ['Linear Regression', 'Logistic Regression', 'RandomForest', 'a3c', 'K.means']}


In [27]:
#Create a new item in machine_learning with the key as 
#learning and the value as all the items from the learning list
machine_learning["Learning"] = Learning

In [36]:
# Create a new item in machine_learning with the key as algorithm_type 
#and the value as all the items from the algorithm_type list:
machine_learning['algorithm_type'] = algorithm_type

In [28]:
print(machine_learning)

{'algorithm': ['Linear Regression', 'Logistic Regression', 'RandomForest', 'a3c', 'K.means'], 'Learning': ['Supervised', 'Supervised', 'Supervised', 'Reinforcement', 'Unsupervised']}


In [29]:
# Remove the a3c item from the algorithm key using the .remove() method:
machine_learning['algorithm'].remove('a3c')

In [30]:
print(machine_learning['algorithm'])

['Linear Regression', 'Logistic Regression', 'RandomForest', 'K.means']


In [31]:
# Remove the Reinforcement item from the learning key using the .remove() method:
machine_learning['Learning'].remove('Reinforcement')

In [37]:
# Remove the Game AI item from the algorithm_type key using the .remove() method:
machine_learning['algorithm_type'].remove('Game AI')

In [38]:
print(algorithm_type)

['Regression', 'Classification', 'Regression or Classification', 'Clustering']


In [39]:
print(machine_learning)

{'algorithm': ['Linear Regression', 'Logistic Regression', 'RandomForest', 'K.means'], 'Learning': ['Supervised', 'Supervised', 'Supervised', 'Unsupervised'], 'algorithm_type': ['Regression', 'Classification', 'Regression or Classification', 'Clustering']}


In [9]:
# import pandas package
import pandas as pd
!ls

AB_NYC_2019.csv                json_example.json
Data Science Workshop.ipynb    overall_topten_2012-2013.csv
Python 3.7                     overall_topten_2012-2013.tsv
csv_example.csv                overall_topten_2012-2013.xlsx
dataset_44_spambase.csv        tas_1991_2016_AUS.csv
excel_example.xlsx             tas_1991_2016_AUS_Activity.csv


In [8]:
# Reading a csv file
df_example = pd.read_csv('csv_example.csv')
df_example

algorithm      learning                          type
0    Linear Regression    Supervised                    Regression
1  Logistic Regression    Supervised                Classification
2         RandomForest    Supervised  Regression or Classification
3              k-means  Unsupervised                    Clustering

In [14]:
!pip install xlrd

  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)


In [16]:
# Reading an excel file
df_excel = pd.read_excel('excel_example.xlsx')
df_excel

algorithm      learning                          type
0    Linear Regression    Supervised                    Regression
1  Logistic Regression    Supervised                Classification
2         RandomForest    Supervised  Regression or Classification
3              k-means  Unsupervised                    Clustering

In [17]:
# Reading a json file
df_json = pd.read_json('json_example.json')
df_json

algorithm      learning                          type
0    Linear Regression    Supervised                    Regression
1  Logistic Regression    Supervised                Classification
2         RandomForest    Supervised  Regression or Classification
3              k-means  Unsupervised                    Clustering

### Exercise 1.02: Loading Data of Different Formats into a pandas DataFrame

In [19]:
!head -3 overall_topten_2012-2013.csv

In [24]:
csv_url = pd.read_csv('overall_topten_2012-2013.csv', skiprows=1)
csv_url

Number  Postcode                                            Suburbs  \
0       1      3029                          Hoppers Crossing, Tarneit   
1       2      3977                    Cranbourne, Devon Meadows, Skye   
2       3      3064  Craigieburn, Donnybrook, Roxburgh Park, Mickleham   
3       4      3030                     Point Cook, Werribee, Derrimut   
4       5      3754                                     Doreen, Mernda   
5       6      3810                                 Pakenham, Rythdale   
6       7      3350  Alfredton, Ballarat, Canadian, Invermay Park, ...   
7       8      3216  Belmont, Grovedale, Highton, Marshall, Waurn P...   
8       9      3136  Croydon, Croydon Hills, Croydon North, Croydon...   
9      10      3805    Fountain Gate, Narre Warren, Narre Warren South   

   Number of Applications  
0                    1069  
1                    1037  
2                     821  
3                     816  
4                     530  
5                     479  
6                     383  
7                     351  
8                     344  
9                     335

In [21]:
# Loading a tsv file
!head -4 overall_topten_2012-2013.tsv

In [27]:
tsv_df = pd.read_csv('overall_topten_2012-2013.tsv', skiprows=1, sep='\t')
tsv_df

Number  Postcode                                            Suburbs  \
0       1      3029                          Hoppers Crossing, Tarneit   
1       2      3977                    Cranbourne, Devon Meadows, Skye   
2       3      3064  Craigieburn, Donnybrook, Roxburgh Park, Mickleham   
3       4      3030                     Point Cook, Werribee, Derrimut   
4       5      3754                                     Doreen, Mernda   
5       6      3810                                 Pakenham, Rythdale   
6       7      3350  Alfredton, Ballarat, Canadian, Invermay Park, ...   
7       8      3216  Belmont, Grovedale, Highton, Marshall, Waurn P...   
8       9      3136  Croydon, Croydon Hills, Croydon North, Croydon...   
9      10      3805    Fountain Gate, Narre Warren, Narre Warren South   

   Number of Applications  
0                    1069  
1                    1037  
2                     821  
3                     816  
4                     530  
5                     479  
6                     383  
7                     351  
8                     344  
9                     335

In [28]:
# Loading xlsx file
!head -4 overall_topten_2012-2013.xlsx

� ��:�	�IvVΫ�E�@�{ĸ�&�������Mׄ�5
� ��:�	�IvVΫ�E�@�{ĸ�&�������Mׄ�5
�-�P�V�_���2Ԕ�ěos���x�lG�D|A��>r#���� �����)�یw�$��ܱ�t����T��{*�I~��PK��v���PK��vO#xl/worksheets/_rels/sheet1.xml.rels��K
�5�A*�~�����#C�6���6j���E���O~2��"K.���(R���<q���2����R������?�m$��D@��d�XÌ�����flaF�56`�*��ʎ�0*�	*�&�@��Rl�bK$;��,H1@�&H����9�� %vQ��D�4H	@�'H�E�9����\�Q


In [30]:
xlsx_df = pd.read_excel('overall_topten_2012-2013.xlsx', skiprows=1, sheet_name=1)
xlsx_df

Number  Postcode                                            Suburbs  \
0       1      3029                          Hoppers Crossing, Tarneit   
1       2      3977                    Cranbourne, Devon Meadows, Skye   
2       3      3064  Craigieburn, Donnybrook, Roxburgh Park, Mickleham   
3       4      3030                     Point Cook, Werribee, Derrimut   
4       5      3754                                     Doreen, Mernda   
5       6      3810                                 Pakenham, Rythdale   
6       7      3350  Alfredton, Ballarat, Canadian, Invermay Park, ...   
7       8      3216  Belmont, Grovedale, Highton, Marshall, Waurn P...   
8       9      3136  Croydon, Croydon Hills, Croydon North, Croydon...   
9      10      3805    Fountain Gate, Narre Warren, Narre Warren South   

   Number of Applications  
0                    1069  
1                    1037  
2                     821  
3                     816  
4                     530  
5                     479  
6                     383  
7                     351  
8                     344  
9                     335

### Scikit-Learn

In [1]:
# Import random classifier from sklearn
from sklearn.ensemble import RandomForestClassifier

In [2]:
rf_model = RandomForestClassifier(random_state=1)

In [3]:
from sklearn.datasets import load_wine
features, target = load_wine(return_X_y=True)

In [4]:
rf_model.fit(features, target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [5]:
preds = rf_model.predict(features)
preds

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [6]:
from sklearn.metrics import accuracy_score
accuracy_score(target, preds)

1.0

### Predicting Breast Cancer from a Dataset Using sklearn

In [7]:
# Import the load_breast_cancer function from sklearn.datasets:
from sklearn.datasets import load_breast_cancer

In [8]:
# Load the dataset from the load_breast_cancer function with the 
#return_X_y=True parameter to return the features and response variable only:
features, target = load_breast_cancer(return_X_y=True)

In [9]:
# Print the variable features:
print(features)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [10]:
# Print the target variable:
print(target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [11]:
# Import the RandomForestClassifier class from sklearn.ensemble:
from sklearn.ensemble import RandomForestClassifier

In [12]:
# Create a new variable called seed, which will take the value 888 (chosen arbitrarily):
seed = 888

In [13]:
# Instantiate RandomForestClassifier with the random_state=seed 
#parameter and save it into a variable called rf_model:
rf_model = RandomForestClassifier(random_state=seed)

In [14]:
# Train the model with the .fit() method with features and target as parameters:
rf_model.fit(features, target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=888,
                       verbose=0, warm_start=False)

In [16]:
# Make predictions with the trained model using the .predict() method and 
#features as a parameter and save the results into a variable called preds:
preds = rf_model.predict(features)
preds

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [17]:
# import the accuracy_score method from sklearn.metrics:
from sklearn.metrics import accuracy_score

In [18]:
# Calculate accuracy_score() with target and preds as parameters:
accuracy_score(target, preds)

1.0

### Train a Spam Detector Algorithm

In [19]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [20]:
!ls

=                              json_example.json
AB_NYC_2019.csv                overall_topten_2012-2013.csv
Data Science Workshop.ipynb    overall_topten_2012-2013.tsv
Python 3.7                     overall_topten_2012-2013.xlsx
csv_example.csv                tas_1991_2016_AUS.csv
dataset_44_spambase.csv        tas_1991_2016_AUS_Activity.csv
excel_example.xlsx


In [21]:
!head -4 dataset_44_spambase.csv

"word_freq_make","word_freq_address","word_freq_all","word_freq_3d","word_freq_our","word_freq_over","word_freq_remove","word_freq_internet","word_freq_order","word_freq_mail","word_freq_receive","word_freq_will","word_freq_people","word_freq_report","word_freq_addresses","word_freq_free","word_freq_business","word_freq_email","word_freq_you","word_freq_credit","word_freq_your","word_freq_font","word_freq_000","word_freq_money","word_freq_hp","word_freq_hpl","word_freq_george","word_freq_650","word_freq_lab","word_freq_labs","word_freq_telnet","word_freq_857","word_freq_data","word_freq_415","word_freq_85","word_freq_technology","word_freq_1999","word_freq_parts","word_freq_pm","word_freq_direct","word_freq_cs","word_freq_meeting","word_freq_original","word_freq_project","word_freq_re","word_freq_edu","word_freq_table","word_freq_conference","char_freq_%3B","char_freq_%28","char_freq_%5B","char_freq_%21","char_freq_%24","char_freq_%23","capital_run_length_average","capital_run_length_l

In [24]:
df_44 = pd.read_csv('dataset_44_spambase.csv')
df_44.head(3)

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   

   word_freq_order  word_freq_mail  ...  char_freq_%3B  char_freq_%28  \
0             0.00            0.00  ...           0.00          0.000   
1             0.00            0.94  ...           0.00          0.132   
2             0.64            0.25  ...           0.01          0.143   

   char_freq_%5B  char_freq_%21  char_freq_%24  char_freq_%23  \
0            0.0          0.778          0.000          0.000   
1            0.0          0.372          0.180          0.048   
2            0.0          0.276          0.184          0.010   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   

   capital_run_length_total  class  
0                       278      1  
1                      1028      1  
2                      2259      1  

[3 rows x 58 columns]

In [25]:
df_44.shape

(4601, 58)

In [26]:
# Understanding what dataFrame.pop is
df = pd.DataFrame([('falcon', 'bird', 389.0),
                   ('parrot', 'bird', 24.0),
                   ('lion', 'mammal', 80.5),
                   ('monkey', 'mammal', np.nan)],
                  columns=('name', 'class', 'max_speed'))
df

name   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [27]:
df.pop('class')

0      bird
1      bird
2    mammal
3    mammal
Name: class, dtype: object

In [28]:
df

name  max_speed
0  falcon      389.0
1  parrot       24.0
2    lion       80.5
3  monkey        NaN

In [29]:
# Extract the response variable using .pop() from pandas.
target = df_44.pop('class')
target.head(4)

0    1
1    1
2    1
3    1
Name: class, dtype: int64

In [32]:
df_44.head(2)

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   

   word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_%3B  \
0              0.0            0.00  ...                   0.0            0.0   
1              0.0            0.94  ...                   0.0            0.0   

   char_freq_%28  char_freq_%5B  char_freq_%21  char_freq_%24  char_freq_%23  \
0          0.000            0.0          0.778           0.00          0.000   
1          0.132            0.0          0.372           0.18          0.048   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   

   capital_run_length_total  
0                       278  
1                      1028  

[2 rows x 57 columns]

In [33]:
# Instantiate RandomForestClassifier
seed = 26
rf_model = RandomForestClassifier(seed)

In [37]:
features = np.array(df_44)

In [38]:
# Train a Random Forest model to predict the outcome with .fit()
rf_model.fit(features, target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=26,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [39]:
# Predict the outcomes from the input data using .predict().
preds = rf_model.predict(features)
preds

array([1, 1, 1, ..., 0, 0, 0])

In [40]:
# Calculate the accuracy score using accuracy_score.
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(target, preds)

0.9991306237774397

### Regression